language: objective-c
osx_image: xcode8
script:
- xctool -project Pipeline.xcodeproj -scheme Pipeline build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)
